# Generated by Django 4.2.5 on 2023-10-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatKAU_main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolinfo",
            name="origin",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
