# Generated by Django 4.2.5 on 2023-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatKAU_main", "0002_schoolinfo_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("majorScore", models.DecimalField(decimal_places=2, max_digits=5)),
                ("generalScore", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
