# Generated by Django 4.2.5 on 2023-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatKAU_main", "0003_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="totalScore",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
