# Generated by Django 4.2.5 on 2023-11-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatKAU_main", "0004_student_totalscore_alter_student_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="year", new_name="studentNumber",
        ),
    ]
