# Generated by Django 4.2.5 on 2023-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatKAU_main", "0005_rename_year_student_studentnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
