# Generated by Django 4.2.5 on 2023-11-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatKAU_main", "0006_student_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="totalScore",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
